### ISSUE TITLE
Add configuration option to disable plugin for packages with binaries

### ISSUE THREAD

**Issue by ghost** [iwink/composer-global-installer#7]
**Is your feature request related to a problem? Please describe.**
Adding packages with binaries will (sometimes) require an update of the "exclude" configuration because not all binaries are set up to find paths in exotic locations through symlinks.

**Describe the solution you'd like**
Add a configuration option "exclude_bin" that automatically disables the plugin for any packages that have a binary defined in their composer.json file.

**Describe alternatives you've considered**
In an ideal situation binaries would always be able to find the location of the project it's being used in. An analysis of which packages do work and why would allow contributions to be made to the packages that do not have binaries that work on exotic locations by symlink.

So I only see this option as a nice to have since you can still define packages in the "exclude" array.

**Comment by danielkoster** [comment]
Ah yes, this sounds like a good idea to introduce. We experience the same issue you describe, we have a certain set of packages which we exclude by default because the binaries just won't work.

This shouldn't be too hard to implement. I think we'll be able to work on this in the next few weeks. If you have any time, a pull request would be greatly appreciated.
