### ISSUE TITLE
Add extra folder under version with hash name for patched packages

### ISSUE THREAD

**Issue by ghost** [iwink/composer-global-installer#8]
**Describe the bug**
Projects with patches will install a version globally. If the composer-global-installer plugin is used for multiple projects one project can start using a patched package from another project.

**To Reproduce**
Setup two projects with the same package in the require section and different patches in the extra section.
Install one project with the iwink/composer-global-installer plugin in a certain global location.
Install the second project with the iwink/composer-global-installer plugin in the same global location.
The second project will simply symlink to the global location as the plugin reports it as being installed?

**Expected behavior**
2 possible solutions
1. Provide exclusion of patched packages (by certain patching plugin packages).
2. Provide support to install patched packages (by certain patching plugin packages) in a hash-named subfolder that coincides with the patched version of the package.

**Additional context**
Exclusion is the easier solution.
Support is the nicer solution.

**Comment by danielkoster** [comment]
This is a bit more tricky to implement, but certainly doable. I'm not 100% sure on how we should do this, as "patches" are not a native composer-feature so we'd have to guess how a plugin manages patches to check if a patched version is used. I believe 9/10 times it's just a "patch" or "patches" key in `composer.json` which we could try to read. Which library do you use to apply patches?

**Comment by ghost** [comment]
I use [cweagans/composer-patches](https://github.com/cweagans/composer-patches) for Drupal projects.

The subfolder may idd be somewhat harder to do. Because patch plugins usually apply the patch after the package is installed in it's installed path. So I think if we want to change the installed path for projects with patches maybe the easiest is to generate a hash generated from the patches settings for that package. But than this will not take into account if the patch applied properly or not.

Also makes me wonder what happens to "unused" global packages. For example when a patch gets removed. At this moment they stay on the system indefinitely. I know that [Letudiant/composer-shared-package-plugin](https://github.com/Letudiant/composer-shared-package-plugin) did implement some data management tracking system. But that is a whole other type of issue.

**Comment by danielkoster** [comment]
I have discussed this issue with the team, but I am afraid we cannot resolve this issue. Applying patches is a custom operation, not something native to composer. Because of that, it is impossible to determine with certainty which packages have been patched.

You can patch packages with the plugin you named, which adds a "patches" key to composer.json. However, it is also possible to provide a file which contains your patches, so we would also need support to parse that file. Patches can also simply be applied through the "scripts" entry with a `patch` command, which the plugin you mentioned also does under the hood. On top of this, there are also other libraries which use more other ways to configure patches.

As long as patches aren't standardized by composer, applying patches will always remain a custom implementation in your project. Custom implementations require custom package installations. Therefor, we are unable to resolve this issue. I have added [a section to the README](https://github.com/iwink/composer-global-installer#packages-with-patches) describing this caveat and how to avoid it.
